config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :webhooks, only: [:create]

  resources :coupons, only: %i[new create]

  get 'successful_coupon_checkout', to: 'coupons#successful_coupon_checkout'

  get 'cancel_coupon_checkout', to: 'coupons#cancel_coupon_checkout'

  get 'successful_order_checkout', to: 'orders#successful_order_checkout'

  get 'cancel_order_checkout', to: 'orders#cancel_order_checkout'

  resources :users do
    resources :orders, except: [:new]
    resources :coupons, only: [:index]
  end

  get '/orders/new', to: 'orders#new'

  resources :cart_items
  resources :carts
  resources :restaurants, only: %i[index show] do
    resources :menu_items, only: %i[show]
  end

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'

    resources :categories
    resources :restaurants do
      resources :menu_items, except: %i[index]
    end
  end

  root 'home#index'
end

app/views/shared/_admin_navbar.html.slim
nav#navbar.navbar.sticky-top.navbar-expand-lg
  .container-fluid.justify-content-start
    a.navbar-brand.text-warning.fs-4 href="/"  Get your foood!
    button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button" 
      span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      ul.navbar-nav.mt-1
        - if user_signed_in? && is_admin?
          li.nav_item
            = link_to 'Dashboard', admin_dashboard_path, class: 'nav-link text-warning'
          li.nav_item
            = link_to 'Categories', admin_categories_path, class: 'nav-link text-warning'  
          li.nav_item
            = link_to 'Add New Restaurant', new_admin_restaurant_path, class: 'nav-link text-warning'
      ul.navbar-nav.ms-auto.mt-1
        - if user_signed_in?
          li.ps-2
            .text-warning#link-to-sign-out
              = link_to "Sign Out", destroy_user_session_path, method: :delete 

app/views/shared/_cart_icon.html.slim
= link_to fa_icon('shopping-cart'), cart_path(@cart), remote: true, class: 'text-warning fa-2x' 

app/views/shared/_cart_modal.html.slim
#cart-modal.modal.fade[tabindex="-1" aria-labelledby="cart-modal" aria-hidden="true"]
  .modal-dialog.modal-lg.modal-dialog-centered
    .modal-content#modal-content

app/views/shared/_footer.html.slim
.footer
  .container-fluid#footer-container
    .row
      .col-8
        .card.bg-dark
          .card-body
            .card-title.fw-bold.text-warning.mb-2
              | About Us
            .card-text.text-light  
              | Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Magna fringilla urna porttitor rhoncus. In iaculis nunc sed augue lacus viverra vitae congue eu. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Proin sagittis nisl rhoncus mattis rhoncus. Et tortor consequat id porta nibh venenatis. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Est ultricies integer quis auctor. Phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet enim. At varius vel pharetra vel turpis nunc.
      .col-2
        .card.bg-dark.d-flex.flex-column.align-items-center
          .card-body
            .card-title.fw-bold.text-warning.mb-2
              | Quick Links 
            .card-text.text-light
              ul.list-unstyled#footer-links
                li = link_to 'About Us', "#"
                li = link_to 'Contact Us', "#"
                li = link_to 'Home', "#"
                li = link_to 'Legal', "#"
                li = link_to 'Privacy Policy', "#"
      .col-2
        .card.bg-dark
          .card-body
            .card-title.fw-bold.text-warning.d-flex.justify-content-center.mb-0
              | We Are Social!
            .card-text.text-warning.d-flex.justify-content-center
              ul.list-unstyled
                li.fas.fa-2x.pb-0 = fa_icon('facebook-square')
                li.fa-2x.pt-0 = fa_icon('twitter-square')
                li.fa-2x = fa_icon('instagram')

app/views/shared/_navbar.html.slim
nav#navbar.navbar.sticky-top.navbar-expand-lg
  .container-fluid.justify-content-start
    a.navbar-brand.text-warning.fs-4 href="/"  Get your foood!
    button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button" 
      span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      ul.navbar-nav.mt-1
        - unless user_signed_in?
          li.nav-item
            = link_to 'Sign In', new_user_session_path, class: 'nav-link text-warning'
          li.nav-item
            = link_to 'Register', new_user_registration_path, class: 'nav-link text-warning'
        li.nav-item
          = link_to "Restaurants", restaurants_path, class: 'nav-link text-warning'
        li.nav-item
          = link_to "Buy Coupon", new_coupon_path, class: 'nav-link text-warning'
        - if user_signed_in? && is_admin?
          li.nav-item
            = link_to "Admin Dashboard", admin_dashboard_path, class: 'nav-link text-warning'
      ul.navbar-nav.ms-auto
        li.ps-2
          .div#shopping_cart
            - if @cart
              = render 'shared/cart_icon'
      ul.navbar-nav.ms-3.mt-1
        - if user_signed_in?
          li.pe-2
            .text-warning#link-to-user-profile
              = link_to current_user.full_name, user_path(current_user)
          li.pe-2
            .text-warning#link-to-user-profile
              = link_to "Your Coupons", user_coupons_path(current_user)
          li.ps-2
            .text-warning#link-to-sign-out
              = link_to "Sign Out", destroy_user_session_path, method: :delete 

app/views/shared/_pagy_nav.html.slim
.pagination.justify-content-center
  == pagy_bootstrap_nav(pagy)

app/views/shared/_restaurants.html.slim
.card.mb-3
  - cache @restaurants do
    - @restaurants.each do |restaurant|
      .card-body
        h5.card-title
          = restaurant.name
        p.card-text
          small.text-muted
            = restaurant.category.name
        p.card-text
          = restaurant.description
        = link_to 'Try it now!', restaurant_path(restaurant), class: "btn btn-info"