config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :webhooks, only: [:create]

  resources :coupons, only: %i[new create]

  get 'successful_coupon_checkout', to: 'coupons#successful_coupon_checkout'

  get 'cancel_coupon_checkout', to: 'coupons#cancel_coupon_checkout'

  get 'successful_order_checkout', to: 'orders#successful_order_checkout'

  get 'cancel_order_checkout', to: 'orders#cancel_order_checkout'

  resources :users do
    resources :orders, except: [:new]
    resources :coupons, only: [:index]
  end

  get '/orders/new', to: 'orders#new'

  resources :cart_items
  resources :carts
  resources :restaurants, only: %i[index show] do
    resources :menu_items, only: %i[show]
  end

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'

    resources :categories
    resources :restaurants do
      resources :menu_items, except: %i[index]
    end
  end

  root 'home#index'
end

app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id           :bigint           not null, primary key
#  active       :boolean          default(FALSE), not null
#  description  :text
#  name         :string           default(""), not null
#  phone_number :string
#  website_url  :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  category_id  :bigint           not null
#
# Indexes
#
#  index_restaurants_on_category_id  (category_id)
#  index_restaurants_on_name         (name) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#
class Restaurant < ApplicationRecord
  default_scope { order(created_at: :desc) }

  scope :active, -> { where(active: true) }
  scope :hidden, -> { where(active: false) }

  belongs_to :category
  has_many :menu_items, dependent: :destroy
  has_one_attached :restaurant_image

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :restaurant_image, attached: true, content_type: ['image/png', 'image/jpg', 'image/jpeg']

  has_paper_trail
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::AdminController
  before_action :find_restaurant, only: %i[show update edit destroy]

  def show
    @pagy, @menu_items = pagy(@restaurant.menu_items, items: 9)
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit; end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      flash[:notice] = 'Successfully added new restaurant!'
      redirect_to admin_restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:notice] = 'Successfully updated restaurant details!'
      redirect_to admin_restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    flash[:notice] = 'Successfully deleted'
    redirect_to admin_dashboard_path
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name,
                                       :phone_number,
                                       :restaurant_image,
                                       :description,
                                       :website_url,
                                       :active,
                                       :category_id)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @pagy, @restaurants = pagy(collection.includes(:category, restaurant_image_attachment: :blob), items: 6)
  end

  def show
    @restaurant = collection.find(params[:id])
    @pagy, @menu_items = pagy(@restaurant.menu_items.available.includes(menu_item_image_attachment: :blob), items: 6)
    respond_to :html, :js
  end

  private

  def collection
    Restaurant.active
  end
end

app/views/admin/restaurants/_form.html.slim
.container
  .col-lg-12.offset-lg-3
    .row.justify-content-center
      .form-row
        .form-group.col-md-6
          = simple_form_for [:admin, restaurant] do |f|
            = f.input :name
            = f.input :phone_number
            = f.input :website_url
            = f.input :description
            = f.input :active
            = f.input :restaurant_image, as: :file, label: "Add image of restaurant", required: true
            = f.association :category, collection: Category.all, prompt: "Select Category"
            = link_to "Cancel", return_to, class: "btn btn-info me-1 mt-2"
            = f.submit "Save", class: "btn btn-warning mt-2"

app/views/admin/restaurants/edit.html.slim
p.fs-2.text-center.text-warning.fw-bolder.font-monospace
 | Edit details of your dish 

= render "admin/restaurants/form", restaurant: @restaurant, return_to: admin_restaurant_path(@restaurant)

app/views/admin/restaurants/new.html.slim
p.fs-2.text-center.text-warning.fw-bolder.font-monospace
  | Add new restaurant
= render '/admin/restaurants/form', restaurant: @restaurant, return_to: admin_dashboard_path

app/views/admin/restaurants/show.html.slim
.container-fluid
  .row
    .col-lg-12
      .card.bg-dark.text-white.mb-2
        - if @restaurant.restaurant_image.attached?
          img.card-img-top#restaurant-show-page-image[src="#{url_for(@restaurant.restaurant_image)}" alt="Restaurant Image"]
        .card-img-overlay.d-flex.flex-column
          .card-body.d-flex.flex-column
            .card-title.text-warning.fs-4.mb-0.d-flex.flex-row
              = @restaurant.name
              - if @restaurant.active? 
                .text-success.d-flex.ms-2 Active
              - else
                .text-danger.d-flex.ms-2 Hidden
            .small.text-info.fs-6.mb-4
              = @restaurant.category.name
            .card-text.fs-5
              = @restaurant.description
            .card-text.mt-3.text-info.fw-bold.d-flex.justify-content-end.mt-auto
              | Phone Number: #{@restaurant.phone_number}
            .card-text.mt-3.fw-bold.d-flex.justify-content-end#restaurant-show-page-link
              = link_to "Link to website", @restaurant.website_url
            .mt-auto
              = link_to fa_icon('arrow-left'), admin_dashboard_path, class: 'btn btn-secondary me-1'
              = link_to fa_icon('trash'), admin_restaurant_path(@restaurant), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger me-1"
              = link_to fa_icon('edit'), edit_admin_restaurant_path(@restaurant), class: "btn btn-info me-1"
              = link_to "Add Dish", new_admin_restaurant_menu_item_path(@restaurant), class: 'btn btn-warning'

      - if @menu_items.present?
        p.fs-3.text-center.pt-3.fw-bold.font-monospace.text-warning
          | Your dishes:
        .container-fluid
          .row
            - @menu_items.each do |menu_item|
              .col-sm-4.mb-2
                .card.h-100.w-100
                  .card-body
                    .card-title.fs-4
                      = menu_item.name
                      - if menu_item.available?
                        p.text-success.text-bold.fs-6
                          | Available
                      - else
                        p.text-danger.text-bold.fs-6
                          | Not available
                    p.card-text
                      = number_to_currency(menu_item.price)
                    p.card-text
                      = truncate(menu_item.description, length: 50, separator: ".")
                    p.card-text  
                      = link_to 'Details', admin_restaurant_menu_item_path(@restaurant, menu_item), class: 'btn btn-info me-1' 
                      = link_to 'Edit', edit_admin_restaurant_menu_item_path(@restaurant, menu_item), class: 'btn btn-warning'
      = render 'shared/pagy_nav', pagy: @pagy