config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :webhooks, only: [:create]

  resources :coupons, only: %i[new create]

  get 'successful_coupon_checkout', to: 'coupons#successful_coupon_checkout'

  get 'cancel_coupon_checkout', to: 'coupons#cancel_coupon_checkout'

  get 'successful_order_checkout', to: 'orders#successful_order_checkout'

  get 'cancel_order_checkout', to: 'orders#cancel_order_checkout'

  resources :users do
    resources :orders, except: [:new]
    resources :coupons, only: [:index]
  end

  get '/orders/new', to: 'orders#new'

  resources :cart_items
  resources :carts
  resources :restaurants, only: %i[index show] do
    resources :menu_items, only: %i[show]
  end

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'

    resources :categories
    resources :restaurants do
      resources :menu_items, except: %i[index]
    end
  end

  root 'home#index'
end

app/models/cart_item.rb
# == Schema Information
#
# Table name: cart_items
#
#  id           :bigint           not null, primary key
#  discount     :decimal(8, 2)
#  price        :decimal(8, )     not null
#  quantity     :integer          default(1)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  cart_id      :bigint
#  menu_item_id :bigint           not null
#  order_id     :bigint
#
# Indexes
#
#  index_cart_items_on_cart_id       (cart_id)
#  index_cart_items_on_menu_item_id  (menu_item_id)
#  index_cart_items_on_order_id      (order_id)
#
# Foreign Keys
#
#  fk_rails_...  (cart_id => carts.id)
#  fk_rails_...  (menu_item_id => menu_items.id)
#  fk_rails_...  (order_id => orders.id)
#
class CartItem < ApplicationRecord
  default_scope { order(created_at: :desc) }

  belongs_to :cart, optional: true
  belongs_to :menu_item
  belongs_to :order, optional: true

  def total_price
    price * quantity
  end

  def check_quantity
    if quantity > 1
      q = quantity - 1
      update(quantity: q)
    else
      destroy
    end
  end

  def discounted_price
    discount&.positive? ? price - (price * (discount / 100)) : price
  end

  def discounted_total
    discounted_price * quantity
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  before_action :create_current_cart, only: %i[create destroy]
  before_action :current_cart_items, only: %i[create destroy]
  before_action :find_cart_item, only: %i[show destroy]

  def show; end

  def new
    @cart_item = CartItem.new
  end

  def create
    menu_item = MenuItem.find(params[:menu_item_id])
    @cart_item = @cart.add_menu_item(menu_item)

    if @cart_item.save
      render '/carts/show'
    else
      render :new
    end
  end

  def destroy
    if @cart_item.check_quantity && @cart.is_empty?
      @cart.destroy
      session[:cart_id] = nil
      redirect_to @cart_item.menu_item.restaurant
    else
      render '/carts/show'
    end
  end

  private

  def find_cart_item
    @cart_item = CartItem.find(params[:id])
  end

  def cart_item_params
    params.require(:cart_item).permit(:menu_item_id)
  end
end

app/views/cart_items/_cart_item.html.slim
- @cart_items.each do |item|
  tr
    td
      = item.menu_item.name
    td
      - if item.discount&. > 0
        .text-decoration-line-through = number_to_currency(item.price)
        .small.text-danger = "#{number_to_percentage(item.discount, precision: 0)} Off!"
        .text-success = number_to_currency(item.discounted_price)
      - else
        .text-success = number_to_currency(item.price)
    td
      | x
      = item.quantity
    td
      .text-success = number_to_currency(item.discounted_total)
    td
      = link_to fa_icon('plus'), cart_items_path(menu_item_id: item.menu_item.id), remote: true, method: :post, data: { 'data-toggle': 'modal', 'data-target': '#modal-window' }, class: 'btn btn-success'
    td
       = link_to fa_icon('minus'), cart_item_path(item), remote: true, method: :delete, data: { 'data-toggle': 'modal', 'data-target': '#modal-window' }, class: 'btn btn-danger'
    

app/views/cart_items/create.js.slim
| $("#modal-window").find(".modal-content").html("
= j (render(@cart))
| "); $("#modal-window").modal("show"); 