config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :webhooks, only: [:create]

  resources :coupons, only: %i[new create]

  get 'successful_coupon_checkout', to: 'coupons#successful_coupon_checkout'

  get 'cancel_coupon_checkout', to: 'coupons#cancel_coupon_checkout'

  get 'successful_order_checkout', to: 'orders#successful_order_checkout'

  get 'cancel_order_checkout', to: 'orders#cancel_order_checkout'

  resources :users do
    resources :orders, except: [:new]
    resources :coupons, only: [:index]
  end

  get '/orders/new', to: 'orders#new'

  resources :cart_items
  resources :carts
  resources :restaurants, only: %i[index show] do
    resources :menu_items, only: %i[show]
  end

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'

    resources :categories
    resources :restaurants do
      resources :menu_items, except: %i[index]
    end
  end

  root 'home#index'
end

app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id           :bigint           not null, primary key
#  active       :boolean          default(FALSE), not null
#  description  :text
#  name         :string           default(""), not null
#  phone_number :string
#  website_url  :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  category_id  :bigint           not null
#
# Indexes
#
#  index_restaurants_on_category_id  (category_id)
#  index_restaurants_on_name         (name) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#
class Restaurant < ApplicationRecord
  default_scope { order(created_at: :desc) }

  scope :active, -> { where(active: true) }
  scope :hidden, -> { where(active: false) }

  belongs_to :category
  has_many :menu_items, dependent: :destroy
  has_one_attached :restaurant_image

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :restaurant_image, attached: true, content_type: ['image/png', 'image/jpg', 'image/jpeg']

  has_paper_trail
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::AdminController
  before_action :find_restaurant, only: %i[show update edit destroy]

  def show
    @pagy, @menu_items = pagy(@restaurant.menu_items, items: 9)
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit; end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      flash[:notice] = 'Successfully added new restaurant!'
      redirect_to admin_restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:notice] = 'Successfully updated restaurant details!'
      redirect_to admin_restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    flash[:notice] = 'Successfully deleted'
    redirect_to admin_dashboard_path
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name,
                                       :phone_number,
                                       :restaurant_image,
                                       :description,
                                       :website_url,
                                       :active,
                                       :category_id)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @pagy, @restaurants = pagy(collection.includes(:category, restaurant_image_attachment: :blob), items: 6)
  end

  def show
    @restaurant = collection.find(params[:id])
    @pagy, @menu_items = pagy(@restaurant.menu_items.available.includes(menu_item_image_attachment: :blob), items: 6)
    respond_to :html, :js
  end

  private

  def collection
    Restaurant.active
  end
end

app/views/restaurants/index.html.slim
.container-fluid
  - cache @restaurants do
    .row.no-gutters
      - @restaurants.each do |restaurant|
        - cache restaurant do
          .col-sm-6.mb-3
            .card#restaurant-index-image-card
              = link_to restaurant_path(restaurant) do
                - if restaurant.restaurant_image.attached? 
                  img.card-img-top#restaurant-index-page-image[src="#{url_for(restaurant.restaurant_image)}" alt="Restaurant Card"]
              .card-body
                .fs-3.card-title
                  = restaurant.name
                p.card-text.small
                  = restaurant.category.name
                p.card-text.fs-6#restaurant-index-page-description
                  = truncate(restaurant.description, length: 180, separator: ".") 
                p.text-end.me-3.mt-4
                  = link_to 'Try it now!', restaurant_path(restaurant), class: 'btn btn-warning'
= render 'shared/pagy_nav', pagy: @pagy

app/views/restaurants/show.html.slim
.container-fluid
  .row
    .col-lg-12
      .card.bg-dark.text-white.mb-3
        - cache @restaurant do
          - if @restaurant.restaurant_image.attached?
            img.card-img-top#restaurant-show-page-image[src="#{url_for(@restaurant.restaurant_image)}" alt="Restaurant Card"]
          .card-img-overlay.d-flex.flex-column
            .card-body.d-flex.flex-column
              .card-title.text-warning.fs-4.mb-0
                = @restaurant.name
              .small.text-info.fs-6.mb-4
                = @restaurant.category.name
              .card-text.fs-5
                = @restaurant.description
              .card-text.mt-3.text-info.fw-bold.d-flex.justify-content-end.mt-auto
                = "Call us: #{@restaurant.phone_number}"
              .card-text.mt-3.fw-bold.d-flex.justify-content-end#restaurant-show-page-link
                = link_to "Visit our website!", @restaurant.website_url
              .mt-auto
                = link_to "Go Back", restaurants_path, class: "mt-auto btn btn-warning"

      - if @menu_items.present?
        - cache @menu_items do
          p.fs-2.text-center.fw-bold.font-monospace.text-warning.pt-2
            | Menu 
          .container-fluid
            .row
              - @menu_items.each do |menu_item|
                - cache menu_item do
                  .col-md-6.mb-2
                    .card.mb-2#menu-item-restaurant-show-card
                      - if menu_item.menu_item_image.attached?
                        = link_to restaurant_menu_item_path(@restaurant, menu_item) do
                          img.card-img-top#menu-item-restaurant-index-image[src="#{url_for(menu_item.menu_item_image)}" alt="Menu item image"]
                      .card-body.d-flex.flex-column
                        .card-title.mt-2.d-flex.flex-row
                          .fw-bold.fs-5 = menu_item.name
                          .text-success.ms-3.fs-5.d-flex.me-auto = number_to_currency(menu_item.price)
                          - if menu_item.discount && menu_item.discount > 0
                            .text-danger.fs-5.d-flex.justify-content-end = "#{number_to_percentage(menu_item.discount, precision: 0)} Off!"
                        .card-text
                          = truncate(menu_item.description, length: 180, separator: ".")
                        .card-text.mt-auto
                          = link_to 'Details', restaurant_menu_item_path(@restaurant, menu_item), class: 'btn btn-info me-1'
                          = link_to fa_icon('shopping-basket'), cart_items_path(menu_item_id: menu_item), remote: true, method: :post, data: { 'data-bs-toggle': 'modal', 'data-bs-target': '#cart-modal' }, class: 'btn btn-warning'

= render 'shared/pagy_nav', pagy: @pagy